import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../api"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
    baseUrl: "http://127.0.0.1:8787/",
});

export const api = createClient(fetchClient);
