name: CI

on:
    push:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    actions: write
    contents: read

jobs:
    lint:
        name: ⬣ Lint
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: ⎔ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.9.0

            - name: 📥 Install deps
              run: pnpm install

            - name: 🔬 Lint
              run: pnpm run lint

    typecheck:
        name: ʦ Types
        runs-on: ubuntu-latest
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: ⎔ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.9.0

            - name: 📥 Install deps
              run: pnpm install

            - name: 🔎 Type check
              run: pnpm run typecheck

    deploy-web:
        name: 🚀 Deploy web
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        needs: [lint, typecheck]
        runs-on: ubuntu-latest
        env:
            # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            GITHUB_REF_NAME: ${{ github.ref_name }}
            GITHUB_SHA: ${{ github.sha }}
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: ⎔ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.9.0

            - name: 📥 Install deps
              run: pnpm install

            - name: ⚙️ Build
              run: pnpm run web build

            - name: 🚀 Deploy web
              run: pnpm run web deploy:prod

    deploy-api:
        name: 🚀 Deploy api
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        needs: [lint, typecheck]
        runs-on: ubuntu-latest
        env:
            # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            GITHUB_REF_NAME: ${{ github.ref_name }}
            GITHUB_SHA: ${{ github.sha }}
        steps:
            - name: ⬇️ Checkout repo
              uses: actions/checkout@v4

            - uses: pnpm/action-setup@v3
              name: Install pnpm
              with:
                  version: 9
                  run_install: false

            - name: ⎔ Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: 22.9.0

            - name: 📥 Install deps
              run: pnpm install

            #   - name: ⚙️ Build
            #     run: pnpm run api build

            - name: 🚀 Deploy api
              run: pnpm run api deploy:prod
